### ISSUE TITLE
[FEATURE REQUEST] Windows / xplatform support

### ISSUE THREAD

**Issue by SKGleba** [Badger-Embedded/badgerd-sdwirec#3]
Hi,

Would be neat to update the readmes with Windows guides.
Not sure if the default driver/manager is meant to work on windows, i ran it under WSL2 with usbipd.
I also ended up writing a python """alternative""" that works on win/lin/macos - [GIST](https://gist.github.com/SKGleba/70a84b43da8185e9a57b8ceb518a3030) - license is MIT, so you can include that too.

Cheers

**Comment by talhaHavadar** [comment]
@SKGleba thats great to hear I will include your python script in this repo and mention it in the website for users. I will close this issue once it is published!

Thanks again for the contribution!

**Comment by SKGleba** [comment]
Hi, that's great to hear.
FYI I just noticed the gist version was slightly older and [had a bug](https://gist.github.com/SKGleba/70a84b43da8185e9a57b8ceb518a3030/revisions#diff-f5d8531ca70b3756986fd1096d98ea6ba0af17daa18d6422a9a7c3bd650152d2) related to bus/vid matching, should be fine now, sorry for the inconvenience!

**Comment by talhaHavadar** [comment]
no problem, just updated the code

**Comment by talhaHavadar** [comment]
It is also published in https://pypi.org/project/sdwirec/0.1.0/ so people can install it via pip
